# Generated by Django 5.0.4 on 2024-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('anons', models.CharField(max_length=250, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('full_text', models.TextField(verbose_name='About')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('picture', models.ImageField(default='car_images/car.jpg', upload_to='car_images/')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
